[package]
name = "starklings"
version = "5.3.0"
authors = [
  "Shramee <shramee@gmail.com>",
	"Liv <mokou@fastmail.com>",
  "Carol (Nichols || Goulding) <carol.nichols@gmail.com>",
]
edition = "2021"

[dependencies]
argh = "0.1"
indicatif = "0.16"
console = "0.15"
notify = "4.0"
toml = "0.5"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"
home = "0.5.3"
glob = "0.3.0"
# Cairo runner dependencies
cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo",tag = "v0.1.0"}

[[bin]]
name = "starklings"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.1"
glob = "0.3.0"
