[workspace]

members = [
    "src"
]

[workspace.package]
version = "1.0.0-alpha.2"
edition = "2023"
repository = "https://github.com/shramee/starklings-cairo1"
license = "MIT"
license-file = "LICENSE"